spring:
  datasource:
    password: jeep
    username: jeep
    url: jdbc:mysql://localhost:3306/jeep
    driver-class-name: com.mysql.cj.jdbc.Driver

       
logging:
  level:
    root: warn
    '[com.promineotech]': debug




